# Generated by Django 4.2 on 2024-07-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_contactinfo1_student1_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo1',
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
        migrations.DeleteModel(
            name='Teacher1',
        ),
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('contactinfo2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo2')),
                ('rollno', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            bases=('testapp.contactinfo2',),
        ),
        migrations.CreateModel(
            name='Teacher2',
            fields=[
                ('contactinfo2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo2')),
                ('subject', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
            ],
            bases=('testapp.contactinfo2',),
        ),
    ]
